Repository part-pantoja/decide, pull requests merged in 2023-12, with the labels that each got.

#58 fix: Arreglo bug de eliminacion de google login.
  decide/authentication/templates/google/login.html
  decide/authentication/templates/registro/loginSinGoogle.html
  decide/authentication/templates/registro/loginSinGoogleEmail.html
  decide/authentication/templates/registro/registry.html
  decide/authentication/views.py
Labels: bug

#68 fix: Problema con el test de voting
  decide/authentication/test_selem.py
  decide/authentication/views.py
  decide/base/tests.py
Labels: bug

#71 Feature/yes no part pantoja2
  decide/booth/templates/booth/booth.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/models.py
Labels: nueva feature

#79 feat(request): envío de mail con la solicitud al censo
  decide/request/models.py
  decide/request/views.py
Labels: nueva feature

#82 Test: Tests unitarios de booth
  decide/booth/tests.py
Labels: tests

#86 fix(request): fallo corregido en los tests de request
  decide/request/tests.py
  decide/request/views.py
Labels: bug

#84 Detalles de votación
  decide/visualizer/templates/visualizer/index.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/models.py
  decide/voting/templates/voting/voting_details.html
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/views.py
Labels: nueva feature

#93 fix(request): solucionado error email request
  decide/request/views.py
Labels: bug

#89 test(booth): Tests de booth con selenium
  decide/booth/test_selem.py
Labels: tests

#100 test(voting): Tests de YesNo
  decide/voting/tests.py
Labels: tests

#101 Feature/booth part pantoja2
  decide/booth/templates/booth/booth_home.html
  decide/booth/test_selem.py
  decide/booth/views.py
Labels: nueva feature

#110 Feature/voting details
  decide/visualizer/templates/visualizer/index.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/models.py
  decide/voting/templates/voting/voting_details.html
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/views.py
Labels: nueva feature

#139 fix(booth): arreglo en los tests
  decide/booth/test_selem.py
Labels: bug

#141 fix(booth): corrección tests de selenium
  decide/booth/test_selem.py
Labels: bug

#142 fix(booth): error headless en test
  decide/booth/test_selem.py
Labels: bug

#144 Feature/new voting type
  .gitignore
  decide/base/migrations/0001_initial.py
  decide/base/migrations/0002_auto_20180921_1056.py
  decide/base/migrations/0003_auto_20180921_1119.py
  decide/booth/templates/booth/booth.html
  decide/booth/urls.py
  decide/booth/views.py
  decide/census/migrations/0001_initial.py
  decide/mixnet/migrations/0001_initial.py
  decide/request/migrations/0001_initial.py
  decide/request/migrations/__init__.py
  decide/store/migrations/0001_initial.py
  decide/store/migrations/0002_vote_voted.py
  decide/store/migrations/0003_auto_20180921_1522.py
  decide/store/models.py
  decide/store/views.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/admin.py
  decide/voting/forms.py
  decide/voting/migrations/0001_initial.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/templates/voting/create_voting.html
  decide/voting/test_selem.py
  decide/voting/tests.py
  decide/voting/views.py
  loadtest/gen_census.py
  loadtest/locustfile.py
Labels: bug, nueva feature, tests

#147 Tests/nuevos tests blankvote
  decide/voting/test_selem.py
Labels: tests

#165 fix: Añadido locust a requirements.txt
  doc/Commits main Git Fame(No recoge todos).jpeg
  doc/Lineas Andres.jpeg
  doc/Lineas Antonio Maqueda.jpeg
  doc/Lineas Gonri.jpeg
  doc/Lineas Pablo.jpeg
  doc/Lineas Raul.jpeg
  requirements.txt
Labels: bug

#166 docs: Documento del proyecto part-pantoja-2
  doc/Documento del proyecto part-pantoja-2.md
  docker/Dockerfile
  docker/docker-settings.py
Labels: documentacion

#170 feat: Añadido nueva verificacion #169
  decide/request/models.py
  decide/request/tests.py
Labels: nueva feature
