Repository part-pantoja/decide, pull requests merged in 2023-11, with the labels that each got.

#26 feat: Añadidas las estadísticas en visualizer
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/models.py
Labels: enhancement

#32 docs: update issue templates
  .github/ISSUE_TEMPLATE/bug-detectado.md
Labels: documentation

#34 docs: Nueva plantilla para las issues de features y tests
  .github/ISSUE_TEMPLATE/issue-para-nueva-feature-o-test-de-una-feature.md
Labels: documentation

#38 feat: Interfaz de creación de votacion
  .github/workflows/django.yml
  decide/authentication/urls.py
  decide/decide/settings.py
  decide/home/views.py
  decide/local_settings.example.py
  decide/voting/forms.py
  decide/voting/templates/voting/create_voting.html
  decide/voting/urls.py
  decide/voting/views.py
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
  docker/instalacionDocker.sh
Labels: enhancement

#41 feat(booth):feature/booth part pantoja2
  decide/booth/templates/booth/booth_home.html
  decide/booth/urls.py
  decide/booth/views.py
Labels: enhancement

#36 feat: crea dos tipos nuevos de votaciones
  decide/booth/templates/booth/booth.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/migrations/0004_alter_voting_postproc_alter_voting_tally.py
  decide/voting/migrations/0005_question_user_response_enabled.py
  decide/voting/migrations/0006_remove_question_user_response_enabled_question_type.py
  decide/voting/models.py
  decide/voting/serializers.py
Labels: nueva feature

#44 feat:feature/yes no part pantoja2
  decide/booth/templates/booth/booth.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/migrations/0007_alter_question_type.py
  decide/voting/models.py
Labels: nueva feature

#23 feat: blank vote option enabled
  decide/voting/admin.py
  decide/voting/migrations/0005_question_is_blank_vote_allowed.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/test_selem.py
  decide/voting/tests.py
  decide/voting/views.py
Labels: nueva feature
